# Service Bind
HOST: "0.0.0.0"
PORT: 80
LOG_LEVEL: "INFO"

# Mysql
DATABASE:
  ENGINE: "mysql"
  DRIVER: "pymysql"
  HOST: "127.0.0.1"
  PORT: 3306
  USER: "root"
  PASSWORD: "123456"
  NAME: "test"

# Redis
REDIS:
  HOST: "127.0.0.1"
  PORT: 6379

